#!/usr/bin/env bash
# configures a new nginx server on ubuntu, create index.html, test it
apt-get update
apt-get -y install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.backup
echo "hello a software development program Rocks!" > /usr/share/nginx/html/index.html
service nginx restart
