#!/usr/bin/env bash
# configures a new nginx server on ubuntu, create index.html, test it
apt-get -y install nginx
service nginx start
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.backup
echo "Holberton School Rocks!" > /usr/share/nginx/html/index.html
