#!/usr/bin/env bash
# configures a new nginx server on ubuntu, create index.html, test it
apt-get update
apt-get -y install nginx
service nginx start
echo 'rewrite ^/redirect_me http://www.davidjohncoleman.com permanent;' >> /etc/nginx/sites-available/default
sudo service nginx restart
