#!/usr/bin/env bash
# configures a new nginx server on ubuntu with a redirect
apt-get update
apt-get -y install nginx
sed -i '46 i \\trewrite ^/redirect_me http://www.davidjohncoleman.com permanent;' /etc/nginx/sites-available/default
service nginx restart
