#!/usr/bin/env bash
# script to check and verify IP's of various subdomains
subs=( www lb-01 web-01 web-02 )
sub=$2
domain=$1
digme () {
    record=$(dig "$1.$2" | awk 'c&&!--c;/ANSWER SECTION:/{c=1}')
    read -ra arr <<<"$record"
    echo "The subdomain $1 is a ${arr[3]} record and points to ${arr[4]}"
}
if [[ -z "$sub" ]]; then
    for s in "${subs[@]}"; do
	digme "$s" "$domain"
    done
elif [[ ! -z "$sub" ]]; then
    digme "$sub" "$domain"
fi
