#!/usr/bin/env bash
# debug NGINX server in Docker Container, then remove the nginx.pid file
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
rm /run/nginx.pid
