#!/usr/bin/env bash
# create an infinite loop with traps for SIGTERM & SIGINT
storage="/var/run/holbertonscript.pid"
thispid=$$
echo "$thispid" > /var/run/holbertonscript.pid
_squit() {
	sudo rm "$storage"
	kill -9 "$thispid"
}
_sterm() {
	echo "I hate the kill command"
	sudo rm "$storage"
	kill -9 "$thispid"
}
_sint() {
	echo "Y U no love me?!"
}
trap _squit SIGQUIT
trap _sterm SIGTERM
trap _sint SIGINT
while (( 1 == 1 )); do
	echo "To infinity and beyond"
	sleep 2
done
