#!/usr/bin/env bash
# This script is displaying "Bootcamp School" 10 times, plus 'Hi' 1 time
i=0
while [ $i -lt 10 ]; do
	echo "Bootcamp School"
	if (( i == 8 )); then
		echo "Hi"
	fi
	(( i++ ))
done
