#!/usr/bin/env bash
# checks if file exists and gives information about it
fn="./holbertonschool"
if [ -e "$fn" ]; then
	echo "holbertonschool file exists"
	if [ -s "$fn" ]; then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f "$fn" ]; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
