#!/usr/bin/env bash
# script to modify the /etc/hosts file with new alias for IP addresses
cat /etc/hosts > ~/hosts.new
N=$(grep -n '127.0.0.1[[:space:]]localhost' ~/hosts.new | cut -b 1)
if [[ "${N}" ]]; then
    sed -i "${N}s/.*/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/" ~/hosts.new
else
    echo -e "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com" >> ~/hosts.new
fi
cat ~/hosts.new > /etc/hosts
rm ~/hosts.new
