#!/usr/bin/env bash
# configures a new nginx server on ubuntu with a 404 error page
# shellcheck disable=SC2154
apt-get update
apt-get -y install nginx
sed -i "30 i \\n\tadd_header X-Served-By $HOSTNAME;\n" \
    /etc/nginx/sites-available/default
service nginx restart
