#!/usr/bin/env bash
# configures a server with HAProxy Load Balancer
apt-get update
apt-get -y install nginx
sed -i "30 i \\\n\tadd_header X-Served-By $HOSTNAME;\n" \
    /etc/nginx/sites-available/default
service nginx restart
